In [1]:
import pandas as pd 
import numpy as np

### 1.Top Expensive Commodities

In [2]:
commodity_stats = pd.read_csv(
    "../data/processed/commodity_statistics.csv"
)

top_expensive = (
    commodity_stats
    .sort_values(
        by="mean_price",
        ascending=False
    )
)

top_expensive.head(10)

,commodity,year,modal_count,mean_price,modal_min,modal_max,variance,standard_deviation,coefficient_of_variation
509,Saffron,2025,26,519896.192308,58000.0,4000000.0,1.579733e+12,1.256874e+06,241.754835
107,Cardamom,2026,13,255484.615385,224300.0,345000.0,8.082244e+08,2.842929e+04,11.127593
109,Cardamoms,2026,32,217018.750000,160000.0,280000.0,1.005087e+09,3.170311e+04,14.608466
108,Cardamoms,2025,308,216474.350649,80000.0,320000.0,1.955450e+09,4.422047e+04,20.427579
652,tulip,2026,8,150000.000000,120000.0,170000.0,3.000000e+08,1.732051e+04,11.547005
599,Tulip,2026,5,132000.000000,120000.0,170000.0,3.660000e+08,1.913113e+04,14.493278
645,poppy seeds,2026,62,119943.580645,60000.0,147700.0,2.719737e+08,1.649162e+04,13.749484
644,poppy seeds,2025,455,116561.949451,2700.0,165000.0,5.303866e+08,2.303012e+04,19.757840
397,Muesli,2025,13,111965.923077,18000.0,225000.0,3.492531e+09,5.909764e+04,52.781806
121,Chakotha,2026,3,106166.666667,4000.0,310000.0,2.077406e+10,1.441321e+05,135.760198

Varience and standard deviation are shown in scientific notation

Certain commodities such as Kankambra and Astera exhibit exceptionally high coefficients of variation (>500%), indicating either highly volatile market prices or the presence of extreme outlier values. These commodities require further investigation before making pricing recommendations

Cheapest Commodities

In [ ]:
cheapest = (
    commodity_stats
    .sort_values(
        by="mean_price",
        ascending=True 
    )
)
cheapest.head()

,commodity,year,modal_count,mean_price,modal_min,modal_max,variance,standard_deviation,coefficient_of_variation
72,Betelnuts,2025,2,3.000000,3.0,3.0,0.000000,0.000000,0.000000
73,Betelnuts,2026,8,3.156250,3.0,3.5,0.045898,0.214239,6.787777
201,Egg,2026,12,8.591667,7.5,9.1,0.170764,0.413236,4.809729
349,Lotus,2025,197,11.837563,3.0,40.0,60.054833,7.749505,65.465375
350,Lotus,2026,2,21.500000,13.0,30.0,72.250000,8.500000,39.534884

### Most Volatile Commodities

In [ ]:
volatile=(commodity_stats.sort_values(by="coefficient_of_variation",ascending=False))
volatile.head()

,commodity,year,modal_count,mean_price,modal_min,modal_max,variance,standard_deviation,coefficient_of_variation
307,Kankambra,2025,265,1055.820755,3.50,100000.0,5.533235e+07,7438.571563,704.529773
40,Astera,2025,454,236.834361,1.20,28000.0,2.594602e+06,1610.776845,680.128017
479,Raibel,2025,208,2350.384615,4.00,170000.0,2.510677e+08,15845.115793,674.149911
147,Cock,2025,1094,473.471920,0.95,42000.0,7.306133e+06,2702.985964,570.886224
292,Jarbara,2025,463,137.714903,1.00,12000.0,6.168933e+05,785.425558,570.327206

As here we can see the coefficient of variation is larger than 100 means outliers present in that commodity

Most Stable Commodities

In [ ]:
volatile=(commodity_stats.sort_values(by="coefficient_of_variation",ascending=True))
volatile.head()

,commodity,year,modal_count,mean_price,modal_min,modal_max,variance,standard_deviation,coefficient_of_variation
51,Bamboo,2026,1,200.0,200.0,200.0,0.0,0.0,0.0
306,Kalmegh,2026,1,9680.0,9680.0,9680.0,0.0,0.0,0.0
577,Thinai (Italian Millet),2026,1,3200.0,3200.0,3200.0,0.0,0.0,0.0
90,Brahmi,2026,1,3500.0,3500.0,3500.0,0.0,0.0,0.0
72,Betelnuts,2025,2,3.0,3.0,3.0,0.0,0.0,0.0

### Best Selling Season

In [3]:
seasonal_csv=pd.read_csv("../data/processed/seasonal_price_summary.csv")
idx = (seasonal_csv.groupby(["commodity", "year"])["avg_modal_price"].idxmax())
best_season=seasonal_csv.loc[idx]
# best_seasons[["commodity","year","season"]]
# best_seasons[best_seasons["commodity"]=="Ajwan"][["commodity","year","season"]]

Worst Selling Season

In [ ]:
idx = (seasonal_csv.groupby(["commodity", "year"])["avg_modal_price"].idxmin())
worst_seasons=seasonal_csv.loc[idx]
worst_seasons[["commodity","season","year","avg_modal_price"]].head()

        commodity        season  year  avg_modal_price
3        Absinthe        Winter  2025      7468.514286
5        Absinthe        Winter  2026      8159.653333
6           Ajwan       Monsoon  2025      7955.244692
11          Ajwan        Winter  2026     12214.711538
13  Alasande Gram  Post-Monsoon  2025      5320.307692

### Highest Price State

In [4]:
state_csv=pd.read_csv("../data/processed/state_commodity_price.csv")
idx=state_csv.groupby("commodity")["avg_modal_price"].idxmax()
state=state_csv.loc[idx]
# high_price_states[["state","commodity","year","avg_modal_price"]].head()

### Highest Price Markets

In [5]:
market_csv=pd.read_csv("../data/processed/market_price_summary.csv")
market=market_csv.groupby("commodity")["avg_modal_price"].idxmax()
market=market_csv.loc[market]
# high_price_market[["state","commodity","year","avg_modal_price","district","market"]].head()

### Fastest Growing Commodities

In [6]:
trend=pd.read_csv("../data/processed/trend_analysis.csv")

positive_trends = trend[trend["month_over_month_percentage_change"] > 0]
high_increase_idx=positive_trends.groupby(["commodity","year"])["month_over_month_percentage_change"].idxmax()
fastest_growth=trend.loc[high_increase_idx]

## making summary table including all columns like mean price ,cv,state,district,market,

In [7]:
stats=pd.read_csv("../data/processed/commodity_statistics.csv")

In [8]:
stats=stats[["commodity","year","mean_price","coefficient_of_variation"]]
best_season=best_season[["commodity","year","season"]]
state=state[["commodity","year","state"]]
market=market[["commodity","year","market","district"]]
fastest_growth=fastest_growth[["commodity","year","month","month_over_month_percentage_change"]]

As stats include all commodity that why we are using it for join we are left join cause want all rows from stats and which rows are presnt in right table will get drop

In [9]:
summary=stats.copy()

In [10]:
summary.shape

(654, 4)

In [11]:
summary=summary.merge(best_season,on=["commodity","year"],how="left")
print("After season:", summary.shape)

After season: (654, 5)

In [12]:
summary=summary.merge(state,on=["commodity","year"],how="left")
print("After season:", summary.shape)

After season: (654, 6)

In [13]:
summary=summary.merge(market,on=["commodity","year"],how="left")
print("After season:", summary.shape)

After season: (654, 8)

In [14]:
summary=summary.merge(fastest_growth,on=["commodity","year"],how="left")
print("After season:", summary.shape)

After season: (654, 10)

In [15]:
summary.head()

,commodity,year,mean_price,coefficient_of_variation,season,state,market,district,month,month_over_month_percentage_change
0,Absinthe,2025,7966.795918,43.383096,Summer,NaN,Neemuch APMC,Neemuch,3.0,72.668613
1,Absinthe,2026,8667.400000,31.235650,Summer,Madhya Pradesh,NaN,NaN,2.0,29.551663
2,Ajwan,2025,8809.395571,32.786019,Winter,NaN,NaN,NaN,12.0,11.166595
3,Ajwan,2026,12226.682181,32.275914,Summer,Andhra Pradesh,Bhopal APMC,Bhopal,2.0,18.190857
4,Alasande Gram,2025,6534.098947,21.242096,Winter,Gujarat,Amirgadh,Banaskanth,12.0,169.812904

In [16]:
summary.to_csv("../data/processed/business_insights_summary.csv",index=False)